// Generated by Wrangler by running `wrangler types`

interface Env {
	UTW_BOT: KVNamespace;
	DISCORD_INVITE: "https://discord.gg/tFgFwCFndp";
	BOT_TOKEN: string;
	BOT_PUBLIC_KEY: string;
	APP_ID: string;
	VERIFY_GUILD: string;
	VERIFY_ROLE: string;
	VERIFY_WEBHOOK: string;
}
