// Generated by Wrangler by running `wrangler types`

interface Env {
	UTW_BOT: KVNamespace;
	DISCORD_INVITE: "https://discord.gg/tFgFwCFndp";
	BOT_TOKEN: string;
	BOT_PUBLIC_KEY: string;
	APP_ID: string;
	VERIFY_GUILD: string;
	VERIFY_ROLE: string;
	VERIFY_WEBHOOK: string;
	VERIFY_CHANNEL: string;
	VERIFY_MESSAGE: string;
	OAUTH_CLIENT_ID: string;
	OAUTH_CLIENT_SECRET: string;
	SECRET_KEY: string;
	WIKI_REST_API: string;
	ZEPTOMAIL_AUTH: string;
	NOTIFICATION_CHANNEL: string;
}
