#:schema node_modules/wrangler/config-schema.json
name = "utw-bot"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
DISCORD_INVITE = "https://discord.gg/tFgFwCFndp"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "UTW_BOT"
id = "767779fec64b44d7b68e922645811353"
