name: Lint

on:
- push
- workflow_dispatch
- pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Node.js
      uses: actions/setup-node@v7
    - name: Run ESLint
      run: npm run lint
